### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by liyingquan** [Pmovil/Toast#2]
I have tried like this:
ant jar
copy dist/Toast.cn1lib to myProject/lib 
refresh lib in IDE
run simulator

but only get the error like below:
java.lang.ClassNotFoundException: com.pmovil.toast.NativeToastImpl
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at java.lang.ClassLoader.findSystemClass(ClassLoader.java:1050)
    at com.codename1.impl.javase.ClassPathLoader.findClass(ClassPathLoader.java:100)
    at com.codename1.impl.javase.ClassPathLoader.loadClass(ClassPathLoader.java:50)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:186)
    at com.codename1.system.NativeLookup.create(NativeLookup.java:55)
    at com.pmovil.toast.Toast.makeText(Toast.java:49)
    at userclasses.StateMachine.onMain_ButtonAction(StateMachine.java:49)
    at generated.StateMachineBase.handleComponentAction(StateMachineBase.java:278)
    at com.codename1.ui.util.UIBuilder$FormListener.actionPerformed(UIBuilder.java:2817)
    at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:345)
    at com.codename1.ui.Button.fireActionEvent(Button.java:393)
    at com.codename1.ui.Button.released(Button.java:424)
    at com.codename1.ui.Button.pointerReleased(Button.java:512)
    at com.codename1.ui.Form.pointerReleased(Form.java:2373)
    at com.codename1.ui.Form.pointerReleased(Form.java:2309)
    at com.codename1.ui.Component.pointerReleased(Component.java:2607)
    at com.codename1.ui.Display.handleEvent(Display.java:1913)
    at com.codename1.ui.Display.edtLoopImpl(Display.java:1009)
    at com.codename1.ui.Display.mainEDTLoop(Display.java:940)
    at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
java.lang.RuntimeException: Toast is not implemented yet in this platform.
    at com.pmovil.toast.Toast.makeText(Toast.java:51)
    at userclasses.StateMachine.onMain_ButtonAction(StateMachine.java:49)
    at generated.StateMachineBase.handleComponentAction(StateMachineBase.java:278)
    at com.codename1.ui.util.UIBuilder$FormListener.actionPerformed(UIBuilder.java:2817)
    at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:345)
    at com.codename1.ui.Button.fireActionEvent(Button.java:393)
    at com.codename1.ui.Button.released(Button.java:424)
    at com.codename1.ui.Button.pointerReleased(Button.java:512)
    at com.codename1.ui.Form.pointerReleased(Form.java:2373)
    at com.codename1.ui.Form.pointerReleased(Form.java:2309)
    at com.codename1.ui.Component.pointerReleased(Component.java:2607)
    at com.codename1.ui.Display.handleEvent(Display.java:1913)
    at com.codename1.ui.Display.edtLoopImpl(Display.java:1009)
    at com.codename1.ui.Display.mainEDTLoop(Display.java:940)
    at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by liyingquan** [comment]
After copying Toast/native to myProject/native,
the error message changed to 
java.lang.RuntimeException: Toast is not supported in this platform.
    at com.pmovil.toast.Toast.makeText(Toast.java:55)
    at userclasses.StateMachine.onMain_ButtonAction(StateMachine.java:49)
    at generated.StateMachineBase.handleComponentAction(StateMachineBase.java:278)
    at com.codename1.ui.util.UIBuilder$FormListener.actionPerformed(UIBuilder.java:2817)
    at com.codename1.ui.util.EventDispatcher.fireActionEvent(EventDispatcher.java:345)
    at com.codename1.ui.Button.fireActionEvent(Button.java:393)
    at com.codename1.ui.Button.released(Button.java:424)
    at com.codename1.ui.Button.pointerReleased(Button.java:512)
    at com.codename1.ui.Form.pointerReleased(Form.java:2373)
    at com.codename1.ui.Form.pointerReleased(Form.java:2309)
    at com.codename1.ui.Component.pointerReleased(Component.java:2607)
    at com.codename1.ui.Display.handleEvent(Display.java:1913)
    at com.codename1.ui.Display.edtLoopImpl(Display.java:1009)
    at com.codename1.ui.Display.mainEDTLoop(Display.java:940)
    at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
    at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)

**Comment by liyingquan** [comment]
Please provide a binary download,thanks!

**Comment by liyingquan** [comment]
It seems to be ok when running on my Android phone, but stil not ok in the simulator.

On my phone,the error changes to be ClassCastException:com.codename1.ui..Container cannot be cast to android.app.Activity

So,the question is how should i invoke ,my code is like below:

---

protected void onMain_ButtonAction(Component c, ActionEvent event) {
        Toast toast = Toast.makeText(super.findContainer(), "Hi there", Toast.LENGTH_LONG);
        toast.show();

---

How can i get the object (addressing android.app.Activity) in codename one ?

**Comment by jegesh** [comment]
+1

**Comment by jegesh** [comment]
I found the answer searching for other examples of getting app context on the cn1 forum.  The application stub class (usually called MyApplication), in the `init()` method, provides the native app context.  The simplest way to get it is do something like this:

```
public class MyApplication {
    private static Object context;

    public void init(Object context) {
        this.context = context;
    }

    public static Object getContext(){
        return context;
    }
...
}
```

Then just call `MyApplication.getContext()` for the first argument of the `Toast.makeToast()` method.
